-- Preventify conversation_audit_log — SaMD Class B audit trail
--
-- Required for CDSCO SaMD Class B compliance and DPDP Act 2023 audit obligations.
-- Every patient-facing turn is recorded here: what was asked, what evidence was
-- retrieved, what the bot responded, and whether any safety constraint fired.
--
-- RULES:
--   - APPEND ONLY. Never UPDATE or DELETE rows from this table.
--   - Written by the pipeline orchestrator (engine/pipeline.py or API handler)
--     AFTER every turn completes — not by phase1_runner or phase2_runner.
--   - Retention: 3 years from created_at (align with DPDP Act 2023 principles).
--   - Access: restricted to clinical reviewers and compliance team.
--   - De-identification: patient_message and bot_response text may be hashed
--     at retention expiry — pending B5 compliance sign-off.
--
-- Populated from:
--   Phase 1 return:  intent, qds_score, _fallback (phase1_fallback)
--   Phase 2 return:  chunks_used, condition_flags_active, query_cache_hit,
--                    reranker_scores, _fallback (phase2_fallback), _fallback_reason
--   Risk Engine:     risk_tier, tier_3_subtype
--   Pipeline:        patient_message, bot_response, session_id, message_id, turn_number

-- ─────────────────────────────────────────────────────────────────────────────
-- Audit log table
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS conversation_audit_log (
    id                      SERIAL          PRIMARY KEY,

    -- ── Patient and session identity ────────────────────────────────────────
    user_id                 TEXT            NOT NULL,   -- UUID (testing) or WhatsApp number (prod)
    session_id              TEXT            NOT NULL,   -- UUID per session — ties turns together
    message_id              TEXT            NOT NULL UNIQUE,  -- UUID per turn (generated by pipeline)
    turn_number             INT,                             -- sequential within session

    -- ── Turn content ────────────────────────────────────────────────────────
    patient_message         TEXT            NOT NULL,   -- patient's original message (English)
    bot_response            TEXT,                       -- NULL for Tier 4 emergency bypass turns
    response_type           TEXT            NOT NULL,   -- see RESPONSE_TYPE values below
    --
    -- RESPONSE_TYPE valid values:
    --   'phase2_response'      → normal RAG pipeline response (Phase 2 ran successfully)
    --   'clarifying_question'  → Phase 1 requested context before Phase 2
    --   'risk_escalation'      → Risk Engine fired Tier 3/4; nudge or emergency message
    --   'phase2_fallback'      → Phase 2 pipeline failed; fallback text returned
    --   'phase1_fallback'      → Phase 1 pipeline failed; fallback used for classification

    -- ── Phase 1 signals ─────────────────────────────────────────────────────
    qds_score               INT,                        -- 1–5 from Phase 1
    intent                  TEXT,                       -- intent enum from Phase 1
    phase1_fallback         BOOLEAN         NOT NULL DEFAULT FALSE,

    -- ── Risk Engine signals ─────────────────────────────────────────────────
    risk_tier               INT,                        -- 0–4 from Risk Engine
    tier_3_subtype          TEXT,                       -- 'foot_wound'|'high_bg'|'hypoglycemia'|NULL

    -- ── Phase 2 retrieval signals ───────────────────────────────────────────
    chunks_used             TEXT[]          NOT NULL DEFAULT '{}',   -- chunk_id list (audit trail)
    condition_flags_active  TEXT[]          NOT NULL DEFAULT '{}',   -- flags that opened Tier 2
    query_cache_hit         BOOLEAN,                    -- True if ANN search was skipped
    reranker_scores         FLOAT[]         NOT NULL DEFAULT '{}',   -- top-5 scores (monitoring)
    phase2_fallback         BOOLEAN         NOT NULL DEFAULT FALSE,
    phase2_fallback_reason  TEXT,                       -- error type string if phase2_fallback

    -- ── Safety constraint signals ───────────────────────────────────────────
    constraint_violation    BOOLEAN         NOT NULL DEFAULT FALSE,  -- True if check_constraints() fired
    constraint_violations   TEXT[]          NOT NULL DEFAULT '{}',   -- list of violation names

    -- ── Audit ────────────────────────────────────────────────────────────────
    created_at              TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);


-- ─────────────────────────────────────────────────────────────────────────────
-- Indexes — support weekly clinical/ops review queries
-- ─────────────────────────────────────────────────────────────────────────────

-- Session lookup (most common query — "show me all turns for this session")
CREATE INDEX IF NOT EXISTS idx_audit_user_session
    ON conversation_audit_log (user_id, session_id);

-- Time-range queries for clinical review
CREATE INDEX IF NOT EXISTS idx_audit_created_at
    ON conversation_audit_log (created_at DESC);

-- Risk tier filter — surface all Tier 3/4 events for clinical review
CREATE INDEX IF NOT EXISTS idx_audit_risk_tier
    ON conversation_audit_log (risk_tier)
    WHERE risk_tier >= 3;

-- Constraint violation filter — find safety failures for ops review
CREATE INDEX IF NOT EXISTS idx_audit_constraint_violation
    ON conversation_audit_log (constraint_violation)
    WHERE constraint_violation = TRUE;

-- Fallback filter — monitor pipeline failure rate
CREATE INDEX IF NOT EXISTS idx_audit_phase2_fallback
    ON conversation_audit_log (phase2_fallback)
    WHERE phase2_fallback = TRUE;

-- QDS distribution (for lead scoring and clinical quality analysis)
CREATE INDEX IF NOT EXISTS idx_audit_qds_score
    ON conversation_audit_log (qds_score);


-- ─────────────────────────────────────────────────────────────────────────────
-- Example queries for clinical/ops weekly review
-- ─────────────────────────────────────────────────────────────────────────────

-- 1. All constraint violations in the last 7 days:
-- SELECT user_id, patient_message, bot_response, constraint_violations, created_at
-- FROM conversation_audit_log
-- WHERE constraint_violation = TRUE AND created_at > NOW() - INTERVAL '7 days'
-- ORDER BY created_at DESC;

-- 2. Phase 2 fallback rate this week:
-- SELECT
--     COUNT(*) FILTER (WHERE phase2_fallback) AS fallback_count,
--     COUNT(*) AS total_turns,
--     ROUND(100.0 * COUNT(*) FILTER (WHERE phase2_fallback) / COUNT(*), 2) AS fallback_pct
-- FROM conversation_audit_log
-- WHERE created_at > NOW() - INTERVAL '7 days'
--   AND response_type IN ('phase2_response', 'phase2_fallback');

-- 3. All Tier 3/4 escalations this week:
-- SELECT user_id, risk_tier, tier_3_subtype, patient_message, bot_response, created_at
-- FROM conversation_audit_log
-- WHERE risk_tier >= 3 AND created_at > NOW() - INTERVAL '7 days'
-- ORDER BY risk_tier DESC, created_at DESC;

-- 4. Chunks retrieved for a specific turn (trace the evidence for a specific response):
-- SELECT c.source, c.section_title, c.grade_priority, c.text
-- FROM preventify_corpus c
-- WHERE c.chunk_id = ANY(
--     SELECT unnest(chunks_used) FROM conversation_audit_log WHERE message_id = '<uuid>'
-- );
